# Data config
data: "data"
rebuild_tensors: True # We save and combine .txt files into tensors for easier training
num_classes: 9

# Toggle activities
train_model: True
bayesian_optimisation: False

# Default model parameters
default_params:
  batch_size: 16
  lr: 0.00020117092107270728
  model_params:
    dropout_rate: 0.4299597919835075
    hidden_dims:
    - 512
    model_type: resnet50
    num_unfrozen_layers: 2
    use_batchnorm: false
    use_dropout: true
    use_pretrained: true
  optimizer: adam
  patience: 16
  weight_decay: 6.433219073535796e-06