# Data config
data: "data"
rebuild_tensors: True # We save and combine .txt files into tensors for easier training
num_classes: 9

# Toggle activities
train_model: True
bayesian_optimisation: True

# Default model parameters
default_params:
  model_params:
    model_type: "resnet50"
    use_pretrained: True
    hidden_dims: [128, 64]
    use_dropout: True
    dropout_rate: 0.25
    use_batchnorm: False
    num_unfrozen_layers: 3
  batch_size: 16
  lr: 0.0001
  weight_decay: 0
  optimizer: "adam"
  patience: 20