bayesian_optimisation: false
class_names:
- Down
- Left30
- Left60
- Left90
- No_Movement
- Right30
- Right60
- Right90
- Up
data: data
default_params:
  batch_size: 16
  lr: 0.00020117092107270728
  model_params:
    dropout_rate: 0.4299597919835075
    hidden_dims:
    - 512
    model_type: resnet50
    num_unfrozen_layers: 2
    use_batchnorm: false
    use_dropout: true
    use_pretrained: true
  optimizer: adam
  patience: 16
  weight_decay: 6.433219073535796e-06
normalization_stats:
  mean: -29.843887329101562
  std: 5.430981636047363
num_classes: 9
rebuild_tensors: true
train_model: true
